version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - PGUSER=admin
      - PGPASSWORD=password
      - PGDATABASE=realworld
      - POSTGRES_USER=admin
      - POSTGRES_DB=realworld
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb:0.11.6
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://admin:password@postgres/realworld?sslmode=disable
    depends_on:
      - postgres
    restart: always
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    tmpfs:
      - /data
